services:
    david63.loginredirect.listener:
        class: david63\loginredirect\event\listener
        arguments:
            - '@config'
            - '@user'
            - '@request'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'
        tags:
            - { name: event.listener }

    david63.loginredirect.admin.controller:
        class: david63\loginredirect\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '@log'
            - '@language'			
